### PR TITLE
Swift 5

### PR DESCRIPTION
**Pull request by finestructure**
Updated targets for Swift 5 and bumped the swift versions where applicable.

I've set up Travis to run on the branch so hopefully the changes in .travis.yml work.

### CODE REVIEW

**Comment by ypopovych** [comment]
Hello,

Thank you for PR!

Can you, please, fix tests? From the first look, it's simply travis.yml fixes (setup proper test environments)

**Comment by finestructure** [comment]
Sure thing, I'll have a look!

**Comment by finestructure** [comment]
Alright, all sorted

**Comment by ypopovych** [comment]
One more comment. Seems as we can install swiftenv from the site, not from GitHub gist.
Check https://swiftenv.fuller.li/en/latest/integrations/travis-ci.html

Can you update config?

**Comment by finestructure** [comment]
Ah yes, makes sense. Copied that around like an ancient relic and never checked back for updated installation instructions :)

**Comment by finestructure** [comment]
Are you planning on pushing out a new release soon?

If you're waiting for #47 - I'm happy to jump in and help with the rebase, seeing as most if not all the conflicts are due to my Swift 5 changes and it looks like adjusting that should be really straightforward when you're familiar with the changes.

**Comment by ypopovych** [comment]
Rebase it, if you can. I will create new release

**Comment by finestructure** [comment]
Here you go: #49

**Pull request merged**
