### PR TITLE
Stable Swift 4 support

### PR DESCRIPTION
**Pull request by jacob-greenfield**
Pull if you want. Stable Swift 4 support, tagged `2.0.0`. Now it is fully working.

### CODE REVIEW

**Comment by ypopovych** [comment]
Hi, @Coder-256 .

Thanks for PR. You did a lot of work.

I want to merge it, but I need several small changed from you:
1. Sign our CLA, please.
2. Restore links to our repo in the "README.md" file.

I will merge it and publish a new version.

Thanks,
Yehor

**Comment by jacob-greenfield** [comment]
I already signed the CLA, but I think you or @dileping still has to. Also, I fixed the README.

**Comment by ypopovych** [comment]
Thanks.

Seems like a bug in clahub. Because we signed it too. (And I saw old PR from you, where you signed it).

I will check everything tomorrow and merge it.

Thanks,
Yehor

**Comment by Coder-256** [comment]
Alright! Could you consider a version bump? (don't forget to update the `xcodeproj`, the podspec, and to run `pod trunk push`)

**Pull request merged**
